apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task1
commonLabels:
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/part-of: task1
resources:
  - prometheus_deployment.yaml
  - prometheus_service.yaml
images:
- name: prom/prometheus
  newTag: v2.23.0
configMapGenerator:
- name: prometheus-configuration
  files:
  - prometheus.yaml
