global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:

- job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'frontend'
  static_configs:
    - targets: ['130.211.44.180:9100']
