apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task1
commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/part-of: task1
resources:
  - grafana_deployment.yaml
  - grafana_service.yaml
images:
- name: grafana/grafana
  newTag: 7.0.0
