apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task1
commonLabels:
  app.kubernetes.io/name: task1-nginx
  app.kubernetes.io/part-of: task1
  app.kubernetes.io/instance: task1
resources:
  - frontend_deployment.yaml
  - frontend_service.yaml
